### ISSUE TITLE
Save buttons have different size. 

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#508]
The problem found during verification https://github.com/ispras/lingvodoc-react/issues/499

Open http://83.149.198.62/dashboard/dictionaries

Can we do anything with Save buttons? They have different size. And it looks very ugly.

![image](https://user-images.githubusercontent.com/59951991/138810022-d0f77307-e09e-4f2e-8fbf-96a6a152b7f1.png)

**Comment by nadezhday** [comment]
логин как админ

dashboard > Dictionaries

Кликаем на любой словарь > Properties

![image](https://user-images.githubusercontent.com/59951991/145966936-f97cc5c0-d6f5-429d-9c8b-acfd39da8f7e.png)


![image](https://user-images.githubusercontent.com/59951991/145967054-112cb0b5-33c5-4885-9367-938d6f03adb1.png)

**Comment by jandrew44** [comment]
Page should be re-designed to have one save button only.

**Comment by myrix** [comment]
Fixed by #734.

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/165247843-b9548cbe-66fc-4cc2-9b98-ac1f0af6ed64.png)

Expected: Page should be re-designed to have one save button only.

Actual: We still have a lot of Save buttons. - NOK

They have the same size. - OK

**Comment by jandrew44** [comment]
I think this case can be closed since it is about buttons size only.
