### ISSUE TITLE
Phonology: wrong transcriptions

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#790]
Open http://lingvodoc.ispras.ru/dictionary/1574/278403/perspective/1574/278408/view, launch Tools -> Phonology, set 'Formant chart threshold' to 1, in the resulting .xlsx file word "тонкий" has transcription "nÃ¦Ã°ek", when it should have transcription "næðek"; transcriptions of some other words are also wrong.

**Comment by myrix** [comment]
Fixed, now in the resulting .xlsx file "тонкий" has transcription "næðek" as expected.

The problem was that some of the markup files were read with the wrong encoding due to the server of http://lingvodoc.ispras.ru/ having and old 1.1.1 version of cchardet package.

Interestingly, it is set as `cchardet==2.1.7` in the server-requirements.txt starting from https://github.com/ispras/lingvodoc/commit/2d3345f4c92cca9b6c8942cef4de79f8d7b564d7, but it looks like the packages were not updated on the http://lingvodoc.ispras.ru/ server then.

Solved by updating packages with `pip install -r server-requirements.txt` and cleaning phonology cache with `redis-cli --scan --pattern "phonology:*" | xargs redis-cli DEL`.

**Comment by nadezhday** [comment]
@myrix 

http://83.149.198.62/dictionary/1574/278403/perspective/1574/278408/view

![image](https://user-images.githubusercontent.com/59951991/170026196-68e137c1-645f-44dd-be83-ed4a9da8656c.png)

xlsx is generated

However, 'тонкий'  is not found in this generated file.

What am I doing wrong?
![image](https://user-images.githubusercontent.com/59951991/170026094-62c51595-326d-4199-add5-f9ce560c1079.png)

**Comment by myrix** [comment]
> @myrix
> 
> http://83.149.198.62/dictionary/1574/278403/perspective/1574/278408/view
> 
> ![image](https://user-images.githubusercontent.com/59951991/170026196-68e137c1-645f-44dd-be83-ed4a9da8656c.png)
> 
> xlsx is generated
> 
> However, 'тонкий' is not found in this generated file.
> 
> What am I doing wrong? ![image](https://user-images.githubusercontent.com/59951991/170026094-62c51595-326d-4199-add5-f9ce560c1079.png)

Looks like at http://83.149.198.62/dictionary/1574/278403/perspective/1574/278408/view there is no markup file attached to lexical entry of "тонкий", cf. http://lingvodoc.ispras.ru/dictionary/1574/278403/perspective/1574/278408/view, so probably test server's DB image should be updated.

**Comment by nadezhday** [comment]
DB was updated, 
However the problem still exists (тонкий is not found in the generated file)
![image](https://user-images.githubusercontent.com/59951991/171151876-0bf2caa4-a4a9-4379-890d-e553ab176c79.png)

@myrix, this case cannot be verified

**Comment by myrix** [comment]
> DB was updated, However the problem still exists (тонкий is not found in the generated file) ![image](https://user-images.githubusercontent.com/59951991/171151876-0bf2caa4-a4a9-4379-890d-e553ab176c79.png)
> 
> @myrix, this case cannot be verified

Looks like the DB is still not up to date to markup additions, at testing http://83.149.198.62/dictionary/1574/278403/perspective/1574/278408/view there is no markup "тонкий.TextGrid", which is present at production http://lingvodoc.ispras.ru/dictionary/1574/278403/perspective/1574/278408/view:
![image](https://user-images.githubusercontent.com/2802467/171153481-1602503c-ea82-4499-8317-5bbfb10a0700.png)

**Comment by nadezhday** [comment]
http://83.149.198.62/dictionary/1574/278403/perspective/1574/278408/view

![image](https://user-images.githubusercontent.com/59951991/172136292-2e002278-2221-4cd1-8f44-9d9b6979fbf1.png)

![image](https://user-images.githubusercontent.com/59951991/172136757-5c8eb825-ea3f-4762-96a3-e91d99af8e6b.png)

Result: 
![image](https://user-images.githubusercontent.com/59951991/172136891-6706618c-3d85-45ac-ac50-eecc5ceb3b60.png)

OK
Verified
